### PR TITLE
Clarified the purpose of the Script Function field

### PR DESCRIPTION
**Pull request by mwittrock**
The Script Function field was not mentioned at all, so I've added a clarification of its use.

Really happy that SAP Integration Suite is now part of the Open Documentation Initiative. Best of luck with it!

### CODE REVIEW

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by Karunaharan** [comment]
Hi @mwittrock - thanks for your feedback. This will be fixed and made available in the next monthly release of the documentation.

Regards,
Karuna

**Comment by SrutiSagaram** [comment]
Closing this as the UA responsible will update documentation

**Review by Karunaharan — APPROVED** [review]

**Comment by mwittrock** [comment]
https://people.sap.com/mortenw

**Pull request merged**
