### PR TITLE
Remove a duplicated sentence from define-a-timer-start-event

### PR DESCRIPTION
**Pull request by rudysap**

### CODE REVIEW

**Comment by MelanieCueppers** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Review by Karunaharan — APPROVED** [review]

**Comment by Karunaharan** [comment]
Thanks for the feedback @rudysap. We will include this change in our next build.

Regards,
Karuna

**Comment by Karunaharan** [comment]
Accepted

**Comment by Karunaharan** [comment]
@rudysap - pls sign the Contributor License Agreement so that I can merge the pull request.

**Comment by Karunaharan** [comment]
@rudysap - pls sign the CLA so that I can merge the pull request.

**Pull request merged**
